Añadir Error

diff --git a/.github/workflows/main_workflow.yml b/.github/workflows/main_workflow.yml
--- a/.github/workflows/main_workflow.yml
+++ b/.github/workflows/main_workflow.yml
@@ -1,10 +1,10 @@
 name: Main Workflow
 
-# S'executarà en fer push a la branca "nodejs_environment_job"
+# S'executarà en fer push a la branca "nodejs_test_error_job"
 on:
   push:
     branches:
-      - nodejs_environment_job
+      - nodejs_test_error_job
 
 jobs:
   linter-execution:
@@ -44,6 +44,13 @@ jobs:
 
       - name: Run Jest Test
         run: npm run test
+        id: jest
+        continue-on-error: true
+
+      - name: Fails
+        if: steps.jest.outcome != 'succes'
+        run: echo "Se ha producido un error" && exit 1
+
   environment_test_execution:
     runs-on: ubuntu-latest
     needs: [linter-execution, test-execution]
